### ISSUE TITLE
Sessions not displaying day of the session

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-schedule-app#122] opened 2015-11-07 15:54 UTC
Not really a bug but I remember we used to have start time displayed as `Day, Time`. eg. Saturday, 10:45 AM .  Is it possible to add it back?

@ryanpitts

**Comment by ryanpitts** [comment] 2015-11-07 17:58
Argh, this was caused by fixing the "All Day" problem. On it.

**Comment by ryanpitts** [comment] 2015-11-07 18:12
fixed in https://github.com/mozilla/mozfest-schedule-loader/commit/8dd17610e2996a8faf2fc2101d6fc7f85ebf6906

**Closed by ryanpitts** 2015-11-07 18:12 UTC
